### ISSUE TITLE
The positional operator did not find the match needed from the query

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#1]
When using this package im getting this error. If I roll back to the master parent repo I dont get the issue.

I think I get this error on the following update operation

````javascript 
Polls.update({ _id: object.pollId, 'answers._id': object.answerId }, {
      $inc: {
        'answers.$.votesCount': votesCount,
        'answers.$.coeficientTotal': coeficientTotal
      }
    });
````

````javascript
message: The positional operator did not find the match needed from the query.
stack:
MongoError: The positional operator did not find the match needed from the query.
    at Function.create (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/error.js:57:12)
    at toError (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/utils.js:123:22)
    at /var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/operations/common_functions.js:379:39
    at handler (/var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/topologies/replset.js:1204:22)
    at /var/app/current/programs/server/npm/node_modules/meteor/npm-mongo/node_modules/mongodb/lib/core/connection/pool.js:405:18
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
````

**Comment by ramezrafla** [comment]
Hey @pmogollons 

Before I dive into it:
1. Why does your selector include `_id` AND `answers._id` ... please replace with `update(object.pollId)`

~~2. The modifier is strange, shouldn't it be~~
```
{ 
    $inc: {
          'answers.votesCount': votesCount,
          'answers.coeficientTotal': coeficientTotal
    }
}
````

[Edit: your modifier is correct .. sorry, never used that syntax before]

**Comment by ramezrafla** [comment]
@pmogollons 

Pls ignore my previous comment, I didn't know enough about positional operators and this affected how I coded the internal update.

I know exactly where the bug is, and will fix it tonight (EST)

**Comment by pmogollons** [comment]
Awesome. I just got it working with cultofcoders version, but would love to get the caching functionality.

Im going to be testing it this week to check that everything works correctly. Thanks

**Comment by ramezrafla** [comment]
@pmogollons 
A new version was pushed, can you try it please?
Thanks

**Comment by ramezrafla** [comment]
@pmogollons 
Any updates? Thanks

**Comment by pmogollons** [comment]
Im going to be testing it later today. Ill let you know in a couple of hours. Thanks.

**Comment by ramezrafla** [comment]
@pmogollons 
Any news? Would love to close this issue

**Comment by ramezrafla** [comment]
Closing, open again if you face any issues

**Comment by pmogollons** [comment]
Looks like its working now. @ramezrafla thanks.

**Comment by pmogollons** [comment]
This issue is still present in another way. The positional operator is not supported by minimongo and a pullrequest adding this feature was closed recentrly. I know this is documented in the readme just wanted to add it here in case someone find this later.

The doc in the DB is updated correctly but the cache is not, there are workarounds for this issue like updating with an index instead of $ like this ```{ array.4.field: newValue }```

But this makes me think, what other mongo operators minimongo is not compatible with and how this will cause issues when adding new update queries in the code base.
