### ISSUE TITLE
Minimongo doesn't support operators in projections yet

### ISSUE THREAD

**Issue by jasongrishkoff** [ramezrafla/redis-oplog#12]
Another minimongo one. Here's the offending code:
```
Chats.find(query,{
  fields:{messages:{$slice:-limit}}, // slice is the problem
  limit:limit,
  sort:sort,
}).fetch()
```
And logs.
```
Exception while invoking method 'getChats' MinimongoError: Minimongo doesn't support operators in projections yet.
I20210211-21:28:23.585(2)?     at MinimongoError (packages/minimongo/common.js:1087:17)
I20210211-21:28:23.585(2)?     at packages/minimongo/local_collection.js:847:13
I20210211-21:28:23.585(2)?     at Array.forEach (<anonymous>)
I20210211-21:28:23.586(2)?     at Function.LocalCollection._checkSupportedProjection (packages/minimongo/local_collection.js:834:23)
I20210211-21:28:23.586(2)?     at Function.LocalCollection._compileProjection (packages/minimongo/local_collection.js:868:19)
I20210211-21:28:23.586(2)?     at Mongo.Collection.find (packages/zegenie:redis-oplog/lib/mongo/extendMongoCollection.js:213:62)
I20210211-21:28:23.586(2)?     at MethodInvocation.getChats (server/methods/chats.jsx:14:31)
I20210211-21:28:23.586(2)?     at MethodInvocation.methodMap.<computed> (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:161:30)
I20210211-21:28:23.586(2)?     at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1771:12)
I20210211-21:28:23.586(2)?     at packages/ddp-server/livedata_server.js:719:19
I20210211-21:28:23.586(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210211-21:28:23.586(2)?     at packages/ddp-server/livedata_server.js:717:46
I20210211-21:28:23.586(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210211-21:28:23.586(2)?     at packages/ddp-server/livedata_server.js:715:46
I20210211-21:28:23.586(2)?     at new Promise (<anonymous>)
I20210211-21:28:23.586(2)?     at Session.method (packages/ddp-server/livedata_server.js:689:23)
I20210211-21:28:23.586(2)?     at packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:52:38
I20210211-21:28:23.586(2)?     at Meteor.EnvironmentVariable.EVp.withValue (packages/meteor.js:1234:12)
I20210211-21:28:23.586(2)?     at Session.sessionProto.protocol_handlers.method (packages/mdg:meteor-apm-agent/lib/hijack/wrap_session.js:51:44)
I20210211-21:28:23.587(2)?     at packages/ddp-server/livedata_server.js:559:43

```

**Comment by ramezrafla** [comment]
Are your documents big? Do you need the slice done by mongo or can you do them yourself?

**Comment by jasongrishkoff** [comment]
Yeah they can get pretty big. I have two types of chats:
1) Chatrooms -- where each message is an individual document connected a `room` field
2) Direct chats -- where each chat is an individual document, but the messages are all stored there.  It's definitely not the most efficient way to have written it (did so about 4 years ago without thinking of the implications).  So my fix to avoid pulling too much data into the client side is to slice it.

**Comment by ramezrafla** [comment]
So this case would be a challenge to cache altogether. Typically documents are kept as atomic as possible and the design of this redis-oplog was meant in that direction (the whole document being cached means we don't have to track the status of each field).

I need to think about this a bit. Maybe have a failsafe that just uses mongodb info and sends relevant changes via redis and that's it (like the previous redis-oplog). Will require an escape hatch per collection at the listener side too.

**Comment by jasongrishkoff** [comment]
What's a bit confusing to me here is that this is a method that does a find/return.  I don't know that it needs `redis-oplog` in this case? I'm primarily concerned about publications and reactive updates. My code actually does something like this for the private chats:

1. Subscribe to the chat, but only pull in the `date` field
2. If the date changes, I fire off a `getChats()` function which does the above `method`

Another example where I use this is for an `artists` collection where they can write a bio.  I save each revision of that bio to a `bio` field within that artist's document, and then when I fetch I project a `{$slice:-1}` to get the most-recent revision.

**Comment by ramezrafla** [comment]
Like the previous redis-oplog, we override the mutation methods (i.e. update, upsert).
If you look at the original redis-oplog, there is often a find - update - find sequence for each mutation which is a killer in performance. In our case, if the doc is cached, it's just a single update (if not cached, a single find and update) as we evaluate the udpated doc with minimongo.

For your case, I think we need to add an override to go back to find - update - find, and let mongo deal with it. The problem, is that each redis listener in the original redis-oplog did a find as well to get the original doc (the changed fields in the received event are actually useless) -- this is done to avoid race conditions: what if the doc changed again while the event is being transmitted.

Give me a couple of days to build this escape hatch. This will also solve the other problems you have raised.

**Comment by ramezrafla** [comment]
@jasongrishkoff 
Meteor released an update to minimongo, have you tested with it?

**Comment by jasongrishkoff** [comment]
Unfortunately I can't test this, sorry.
