### ISSUE TITLE
Lacking 'transform' support in find options

### ISSUE THREAD

**Issue by fumbleforce** [ramezrafla/redis-oplog#18]
When trying to integrate this package with `jagi:astronomy`, I encountered an issue that this fork, when retrieving from the cache, it does not apply the `transform` function which is an optional function passed to `find` and `findOne`. This makes the package not fully compatible with the official docs, or with Astronomy which relies on transforms.

https://docs.meteor.com/api/collections.html#Mongo-Collection-find

**Comment by ramezrafla** [comment]
Thanks @jorgeer 
On it

**Comment by ramezrafla** [comment]
Should be functional now, pls open another issue if still facing this
