### ISSUE TITLE
Document of what is being published to redis

### ISSUE THREAD

**Issue by weisheng-p** [ramezrafla/redis-oplog#2]
I'm the middle of writing a changestream to redis-oplog nodejs process, and decided to go with this fork.
I noticed that there is a bit of change on the data that is being published to redis compared to the original fork.
Do you have a full document of what is being published?

**Comment by ramezrafla** [comment]
Hi @weisheng-p 

If you could implement a changestream that would be fantastic and even more scalable! 

1 For inserts, we send the whole document that was inserted (with all the fields and their values)
2. For updates we only send the fields that changed (we a diff between mutated and original and keep the changed fields only) and their values in addition to `_id`. The 'f' (i.e. Fields) in the message are the **top level fields** that saw any change
3. For removes we only send the _id, e.g. `{_id:'12345'}`

You can see this in `mongo/Mutator` and in `redis/RedisSubscriptionManager.process`

To do a test, launch `redis-cli monitor` in your dev instance to see the messages coming through

**Comment by ramezrafla** [comment]
@weisheng-p 
How can we work together on this? I am happy to share edit of this repo or merge your PRs
Would be great if we can reduce failure points and dispose of redis completely

**Comment by weisheng-p** [comment]
@ramezrafla thanks for this.
I'm actually trying to solve a different problem.
I've a separate system that also do updates on the same mongodb instances that would requires a separate redis pusher for this to happen. 
so this would be a separate nodejs process that run alongside with meteor process, similar to how the OplogToRedis Go project works.

**Comment by ramezrafla** [comment]
Understood @weisheng-p 

A quick note about OplogToRedis, is that it only sends the fields that changed, expecting redis-oplog to query the DB for the values. 

On the other hand, we always send the values down (our express goal is to reduce db load to be scalable). It means we cannot use OplogToRedis but also that you need to send the values too in your `doc` field in your redis message.

**Comment by weisheng-p** [comment]
@ramezrafla thanks for the tip.
I do intend to send the updated value to redis, to prevent that one more lookup.
Is there a option to disable that or is that not implemented right now?

**Comment by ramezrafla** [comment]
Hi @weisheng-p 
Right now you MUST send update values. Everything around this repo is designed to reduce DB hits, so there is no option to alter this behavior as it's fundamental to its philosophy

**Comment by ramezrafla** [comment]
@weisheng-p 
Checking in, all is well?
Let me know if you need anything or we can close this issue
