### ISSUE TITLE
Issue with cache and undefined selectors

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#5]
When you dont pass a selector to a find or findOne it doesnt has the same behaviour as normal meteor collections and it will return no documents.

I think this is an issue with MiniMongo which you are using for caching. The workaround is to just use ```{}``` as the selector.

```javascript
Collection.startCaching();
const docs = Collections.find(); // No documents
const docs2 = Collections.find({}); // n documents in collection
```

**Comment by pmogollons** [comment]
I think is only happening on findOne. Adding a default value in line 108 in extendMongoCollection.js fixes the issue.

```javascript
this.findOne = function(selector = {}, options) {...}
```

**Comment by ramezrafla** [comment]
Ok - will make the change

**Comment by ramezrafla** [comment]
Pull pls - v 2.0.8

**Comment by pmogollons** [comment]
Fixed. Thanks.

Pd: I'll start creating PR's when possible from now on. Just wanted to know if that had a reason before changing it.
