### ISSUE TITLE
Behaviour in fields on find is different than in Mongo Collection

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#6]
When you set a projection (fields) option in a find or findOne query having the following schema and projecting the parent field the nested fields wont be fetched.

```javascript
// Schema
{
  _id: String,
  someObject: {
    _id: String,
    other: Number
  }
}

// Mongo Collection find
Collection..findOne({}, { fields: { someObject: true } }); // someObject contains _id and other fields

// Cached collection
CachedCollection.findOne({}, { fields: { someObject: true } }): // someObject is empty
CachedCollection.findOne({}, { fields: { someObject: { _id: true, other: true } } }): // someObject contains _id and other fields
```

**Comment by ramezrafla** [comment]
We use MiniMongo's projector, so it should have exact behavior vs the standard

Have you tried replacing `true` with `1`

**Comment by ramezrafla** [comment]
I just did a test using `Meteor shell`

And I can't replicate your behaviour

```
> Meteor.users._isCached
true
> Meteor.users.findOne({}, {fields:{emails:1}})
{
  emails: [ { address: 'admin@none.com', verified: false } ],
  _id: 'aNgTfB4AhPg6qv6XW'
}
> Meteor.users.findOne({}, {fields:{emails:true}})
{
  emails: [ { address: 'admin@none.com', verified: false } ],
  _id: 'aNgTfB4AhPg6qv6XW'
}
```

**Comment by ramezrafla** [comment]
```
> Meteor.users.findOne({}, {fields:{services:true}})
{
  services: {
    password: {
      bcrypt: '$2b$10$92Ad58q1Sgae7/Avvw.....'
    }
  },
  _id: 'aNgTfB4AhPg6qv6XW'
}
```

**Comment by ramezrafla** [comment]
What was the issue?

**Comment by pmogollons** [comment]
Not sure, after restarting the system today I couldnt reproduce it. Im going to keep testing and will let you know. Thanks

**Comment by pmogollons** [comment]
Unfortunately im getting again this issue. Ill reopen and create a reproduction later so that the problem can be identified.

**Comment by ramezrafla** [comment]
Hi @pmogollons 

I would be very grateful if you could isolate a test case. The Meteor team will shortly release a blog post about this (I'll make sure you are mentioned as an early adopter and tester). I don't want to push to the community when there is an outstanding issue.

Thanks so much!

**Comment by pmogollons** [comment]
Hi @ramezrafla, sure give me an hour I finish a task im on right now and ill try to create the repro.

**Comment by pmogollons** [comment]
Im still having issues reproducing it. It not happening most of the times, bu im supposing that its an issue where the cache gets corrupted, maybe some fields are removed or not saved to the cache at some point. Up till now it has only happened with nested fields.

I tried to reproduce the exact scenario but it works, so not sure how to get to the issue, but ill try to describe this scenario as maybe you have some insight.

I have a collection where I create a document, and in the ```afterInsert``` hook I call an api that returns an object and then i update this document with that data in an object fielf ```{ zoomData: { ...apiData } }``` (Probably the issue is here and the cache doesnt get the updated data for some reason).

After this I have a method call that tries to get the data from that document and if I use ```{ fields: { zoomData: true } }``` I dont get the nested fields, but id I do ```{ fields: { zoomData: { field1: true, field2: true, field3: true } } }``` I do get the nested fields. Initially I though it could be a minimongo issue as in the past I saw that this could happen, but looks like that has been solved now.

So, im guessing now that the issue is that the cache is not getting updated with the data that is retrieved on the after insert hook.

Ill keep trying to reproduce it in isolation, but up till now I havent been able to do it.

Also this is how my settings looklike.

```json
{
  "redisOplog": {
    "redis": {
      "globalRedisPrefix": "LOCAL:"
    },
    "mutationDefaults": {
      "optimistic": false
    }
  }
}
```

**Comment by ramezrafla** [comment]
@pmogollons 

Can you try something, `console.log` both selectors (topfield projected and subfields projected). So when you get it reproduced you can check if it's the issue. The fact that subfields work but not topfields is strange, it does mean the doc is updated. You could also do a `console.log` of `collection.getCache(_id)` to see the full doc.

Can you send me your `afterInsert` hook method? Maybe something there.

**Comment by ramezrafla** [comment]
In mutator we have this code for inserts.
```
const docId = Originals.insert.call(this, data)
const doc = { ...data, _id:docId }
this.setCache(doc)
```

There could be a bug here. We `setCache` AFTER we do the insert in the DB. Which means AFTER your hook. Could that be the issue?

**Comment by ramezrafla** [comment]
Not sure .. is `zegenie:redis-oplog` at the top of your packages?

**Comment by pmogollons** [comment]
You are right, the cache is update if the nested fields actually return the content. Ill try that and the getChache and let you know.

Does the setCache run after the hook is completed? If so that could be the issue, I coul try to set it on before inert hook instead.

This is my hook. I do have the package as the first one in my packages file.

```javascript
Assemblies.after.insert(function assembliesAfterInsert(userId, doc) {
  Promise2.await(sendAssemblyNotification(doc));

  const folderId = Folders.insert({ name: doc.title, condoId: doc.condoId, assemblyId: doc._id });

  const assembly = Assemblies.createQuery({
    $filters: {
      _id: doc._id
    },

    condo: {
      cover: true,
      nameShort: true
    }
  }).fetchOne();

  const zoomData = ZoomClient.createMeeting({ ...assembly, ...doc });

  Assemblies.update({ _id: doc._id }, { $set: { zoomData, folderId } });

  Events.direct.insert({
    condoId: doc.condoId,
    name: doc.title,
    image: assembly.condo.cover,
    startsAt: doc.fromDate,
    endsAt: doc.toDate
  });
});
```

**Comment by ramezrafla** [comment]
Ok, so if the cache value are set properly, we have no issues with the hook then. The issue is elsewhere.
I did a quick look at the mongocollection-hooks package and if it runs after zegenie:redis-oplog insert there should be no issues.

Look forward to your results once you get those `console.log` outputs

**Comment by pmogollons** [comment]
I've got very weird results. The first ```findOne``` deoesnt return the data correctly the data that is updated from the hook.

The getCache returns without the data of the hook and after making a change to the server that removes the cache the data appears and everything works normally again.

What I think it happens its that ```update``` in hook runs before cache is set with the insert data, this causes the cache to be incomplete, then the server restarts and the cache is cleared so everything is retrieved from the DB and now the cache is up to date.

**Comment by pmogollons** [comment]
The issue finally is not with the projection on fields, is in the way the cache is set after the hooks run but without all the data that should be available after the hooks run, the update data is sent over redis but it has no document to update on the cache as is not yet set.

This can be worked around by using a before hook instead of an after hook, but will be better if this wont happen, and if its hard to do we should at least have some **Known issues** segment on README so that we can know about it.

**Comment by ramezrafla** [comment]
@pmogollons 

I think you may have race conditions between the hook and redis sending the data back.
If you set optimistic to `true`, does it fix it?

When you set optimistic to off, we listen to redis which is delayed vs your hook.

**Comment by ramezrafla** [comment]
Another issue, are you making the changes during a method call (i.e. client is waiting for response, not a deferred call from within a method)? theo added a check to force optimistic to off when it's purely a server update

**Comment by ramezrafla** [comment]
Set `{optimistic:true}` in your `insert` or `update` to force optimistic and check if it works pls

**Comment by pmogollons** [comment]
Still the same issue with optimistic: true, both in the insert and the update. I even tried using the before hook and it also has the issue, the cache is empty while in the DB the data is there. I think I can create a reproduction now, give me a sec ill try to do that.

**Comment by pmogollons** [comment]
Here is the repro. https://github.com/pmogollons/redis-oplog-issue

Open Chrome in localhost:9000 and go to the console and run

```javascript
Meteor.call('test'. console.log);
```

It will return the result from getcache, findOne and rawCollection findOne so that you can compare what are the values from each one.

**Comment by ramezrafla** [comment]
I was thinking: If we implemented the hooks inside this package, would that suffice? One of the things I hate is all these packages right and left that complicate deployment and maintenance.

**Comment by pmogollons** [comment]
The issue with that is that other packages already use collection_hooks package so it will break those. Also I think is usually better to have separate packages in case you only want one thing, like cache or redis or hooks, but you can have the 3 packages to work together to have the full benefits. But thats just me.

**Comment by ramezrafla** [comment]
@pmogollons 

First, thanks for the repo, it helped isolate the problem

So this is a dicey one. The `collection_hooks` package affects the doc upon call to the original `Mongo.insert`. So we never see the change at our end as it happens in the background. It's opaque by design (which makes sense as there was no need to access to doc)

Without major rework, there are 4 alternatives I see.
1. For this redis-oplog package to replace the `before` hooks but do it super simple -- no userId or overloading the context with methods like `getTransform` etc. I did a quick test and it worked. This is dangerous as people who are already using `collection-hooks` will see their code failing
2. We do a refetch of the doc after the `insert`, but that's another DB hit -- this is something you would do in the `after` hook (see next point for better solution)
3. Add an `after` hook where you do a cache update (`setCache`)
4. Move the `before` hook to `after` and do an update to the doc

**Comment by pmogollons** [comment]
No problem. So I have been thinking about it and this is not a huge (for me at least) as I use hooks very lightly. Probably 2 or 3 will be the best options as I dont use this kind of hooks on collections that have high throuhput.

As far as I checked the after hook was also failing so alternative number 4 wont work.

Would you mind if we have a chat on meteor community slack?

**Comment by ramezrafla** [comment]
Hi @pmogollons 
Please accept my apologies for the delay. Life gets in the way sometimes.

I just pushed a new branch called `hooks`, it implements the same hooks in `collection-hooks` with 4 notable exceptions:
1. We don't get the `userId` in a publication -- maybe we do, we didn't test it yet
2. We don't yet support `upsert` hooks, we'll get to it later if need be -- laziness as we don't use it often in our app
3. We don't support `this.getTransform` inside the hooks (and I don't think we need to, honestly)
4. `before.find` and `before.findOne` hooks are stored together, same for `after.find` and `after.findOne`

The hooks (`direct`, `before`, `after`) are only added if you call `startCaching` otherwise you fall back on `collection-hooks`

I tested your repo and it works well now with this setup. Please let me know if it solves your problem in your app.

In terms of community slack, sure. Do you have the link? Can we shoot for Monday or Tuesday?

**Comment by ramezrafla** [comment]
I should also mention that I did not test all the hooks, just `before.insert`, `after.insert`, `after.update` and `after.remove`
(We use `after` only in our app). 

However, this should give the right confidence as there is redundancy between `before` and `after` handlers.

**Comment by pmogollons** [comment]
Hey no issues. Im going to test again today with the new branch and will post here again. Thanks.

Here is the link to the slack, im almost always connected.
https://join.slack.com/t/meteor-community/shared_invite/zt-a9lwcfb7-~UwR3Ng6whEqRxcP5rORZw

**Comment by ramezrafla** [comment]
@pmogollons 
I merged the `hooks` branch back into `master` and fixed a minor issue in `upsert`
I tested with my app and it's now used in production

Can you confirm if all is well so we can close, time to go public in the community!

**Comment by pmogollons** [comment]
@ramezrafla sorry for not answering until now. This new version with the hooks fix is not working for me, the hook runs but the document is not created.

Even if I remove my hook the document is not created, and no error is thrown.

If I checkout a9c2175287cce666b21f93fd06e7776d5086e506 I dont get this behaviour.

**Comment by ramezrafla** [comment]
So a9c2175 works perfectly for you?

**Comment by pmogollons** [comment]
Sorry, not that one the commit before hooks (a9931e6931510a257e4fe887ae439b9fff15d76b).

But I just got a simple workaround, just use a timeout. In my case this is a very simple operation so for me this is good enough workaround.

I still will check in what point the hooks are not working so that you can check where is the issue.

**Comment by pmogollons** [comment]
Just found the issue is not that the document doesnt exists, but the simpleschema autovalues are not getting generated so the createdAt value is not present and it makes my query dont show the document as the first one.

So the issue now is that this new hooks implementation is messing with simpleschema and collection2.

**Comment by pmogollons** [comment]
I just updated the issue repository with this issue.

**Comment by ramezrafla** [comment]
You are right!
An oversight in overloading when setting up hooks (actually, it's a bit tricky -- thank goodness for Node debugger)

Can you do a pull of the latest version and test it

PS: Thanks for updating the redis-oplog-issue repo, that's what I used to figure it out

**Comment by pmogollons** [comment]
well I just rolledback the workarounds and this is now working in the cases it was not before. Thanks

Im going to keep testing on staging and hopefuly ill be able to try it in production next week if there are no issues.
