### ISSUE TITLE
Issue when using $unset on updates

### ISSUE THREAD

**Issue by pmogollons** [ramezrafla/redis-oplog#7]
I think there is probably an error in how $unset is handled, maybe because it has no value and now we are not doing a find after update so $unset updates are not reactive.

```javascript
Assemblies.update({ _id: poll.assemblyId }, { $unset: { currentActivePollId: true } });
```

This piece of code is not reactive using this package, but it is when using cultofcoders one.

**Comment by ramezrafla** [comment]
You're right, the way this `redis-oplog` works is by sending the changed fields via redis to the other instances and internally to change listeners. The way the original `redis-oplog` does things, is by querying the DB for the new doc. I don't use `$unset` in my app so never faced this.

A solution would be to `{$set:{field:undefined}}` -- let me play with it a bit and see if I can fix this easily

**Comment by ramezrafla** [comment]
@pmogollons 
I made a change to handle $unset properly, can you pull and try it again?

**Comment by pmogollons** [comment]
Still not working, let me create a reproduction so that it can be tested correctly.

**Comment by ramezrafla** [comment]
Ok, so something else is happening downstream. It worked on my end.
The reproduction repo will make sure I solve it right, thanks!

**Comment by ramezrafla** [comment]
@pmogollons 
Any news? Is it working now? 
As mentioned, it worked on my side

**Comment by pmogollons** [comment]
Hi, sorry for the delay. Here is the reproduction in its simplest form. Just a meteor create --react with a few changes and redis-oplog package added.

https://github.com/pmogollons/ro-issue

**Comment by ramezrafla** [comment]
Thanks @pmogollons, that repo was very helpful indeed
So the bug was in observers which failed to see the cleared fields. Pull now pls and try again

Thanks

**Comment by pmogollons** [comment]
Awesome, it works now. And the code looks more understandable (not that I do undersand it completly yet) 😂

Ill start testing this in staging and let you know if something else comes out. Thanks!

**Comment by ramezrafla** [comment]
Thanks - it took a long time to understand the original code, many authors, conflict of approach, dead code etc.
I did my best to clean it up.

The changes are to 
1. Send in the messages list of `cleared` fields and 
2. Set these fields 'undefined' in redis listener to trigger `cleared` message in observers to client.
