### ISSUE TITLE
collection.startCaching() on Meteor.users

### ISSUE THREAD

**Issue by jasongrishkoff** [ramezrafla/redis-oplog#8]
Should I enable `collection.startCaching()` on Meteor.users? A bit unclear on this.

**Comment by jasongrishkoff** [comment]
Okay based on the positive results from `Meteor.call('__getCollectionStats','users',console.log)` seems like caching this collection is the right thing to do.

**Comment by ramezrafla** [comment]
@jasongrishkoff 
Super sorry - missed the first message. Yes! You should cache `users`. Typically every method call requires some sort of user roles validation, so calls to this collection are frequent and expensive. Also, you rarely have to link to many other user profiles for a given user. 

Let me know how your results are looking and any issues you face.

**Comment by jasongrishkoff** [comment]
Thanks @ramezrafla.  I wanted to try this because the original version of `redis-oplog` was causing some issues in my chatrooms whereby it seems to randomly stop pushing updates to users and they have to refresh to get the latest chats.

Yours seemed to be working really smoothly on my dev env, but as soon as I pushed it to production (3x Galaxy quad containers) all of them crashed hit ~100% CPU, publications stopped returning, and I had to roll everything everything back. Not entirely sure where it went wrong. Checked Mongo Atlas and all was fine.  The redis server I had set up was also hanging out at < 1% CPU usage.

I wonder if it has something to do with the caching I had set up on my major collections -- maybe too much happening at once? Hard to say.

**Comment by ramezrafla** [comment]
@jasongrishkoff 
Do you have logs I can look at?

100% CPU is quite strange -- we barely hit 50% during deployment then are at 10% at the most on a given day.
I am happy to jump on a video call to do a quick revue of what's happening.

1. What I do to test it is have 2 meteor instances (one at :3000 and another at :3004) and see if the communication between them is going well.
2. Call `redis-cli monitor` to see the messages flowing back and forth, could provide hints
